name: Build
on: [ push, pull_request ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.13, 1.14, 1.15]
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Upload coverage to Codecov
      timeout-minutes: 5
      run: curl -s https://codecov.io/bash | bash
